// Reproduce the bundled, unmodified upstream fonts/CSS from package-lock.json.
import fs from 'node:fs';
import path from 'node:path';
const source = 'node_modules/@fortawesome/fontawesome-free';
const target = 'app/src/main/assets/shared/fontawesome';
const { version } = JSON.parse(fs.readFileSync(`${source}/package.json`, 'utf8'));
fs.mkdirSync(`${target}/css`, { recursive: true });
fs.mkdirSync(`${target}/webfonts`, { recursive: true });
fs.copyFileSync(`${source}/css/all.min.css`, `${target}/css/all.min.css`);
fs.copyFileSync(`${source}/LICENSE.txt`, `${target}/LICENSE.txt`);
for (const name of fs.readdirSync(`${source}/webfonts`)) {
  if (name.endsWith('.woff2')) fs.copyFileSync(`${source}/webfonts/${name}`, `${target}/webfonts/${name}`);
}
const metadata = JSON.parse(fs.readFileSync(`${source}/metadata/icon-families.json`, 'utf8'));
const icons = [];
for (const style of ['solid', 'regular', 'brands']) {
  for (const file of fs.readdirSync(`${source}/svgs/${style}`).sort()) {
    const name = path.basename(file, '.svg');
    const meta = metadata[name];
    icons.push({ name, style, label: meta?.label || name, terms: meta?.search?.terms || [] });
  }
}
// Script form keeps the Store's connect-src 'none' policy intact.
fs.writeFileSync('app/src/main/assets/store/icon-catalog.js',
  `/* Generated by tools/vendor-icons.mjs. Font Awesome ${version}, CC BY 4.0. */\nwindow.hermitIconCatalog = ${JSON.stringify({ version, icons })};\n`);
console.log(`Bundled Font Awesome Free ${version}: ${icons.length} icon/style combinations, all WOFF2 fonts.`);
